;After FINDKEYCODE, the index of keypad is stored at KEY(30H)
;up이 17번째, left가 21번째, down이 22번째, right가 23번째 index값임
;key에 0,1,2,3 저장(순서대로 up, right, down, left)

DATAOUT     EQU	0FFF0H
DATAIN      EQU	0FFF1H
COLRED		EQU	0FFC6H
ROW		    EQU	0FFC7H
SNAKE_DIR	EQU 31H

SAMPLEKEY:
			PUSH	PSW
			SETB	PSW.4
			SETB	PSW.3
			CALL	KEYINITIAL
			JB		ACC.3, PASS; 4는 잘못된 키를 눌렀거나 키 입력이 없을 때
			MOV		SNAKE_DIR, A
			CALL	BOUNCE
			POP		PSW
			RET

PASS:
			POP		PSW
			RET

BOUNCE:
			CALL	KEYDELAY
RELOAD		MOV		A, #0
			CALL	SUBKEY
			CPL		A
			JNZ		RELOAD
			CALL	KEYDELAY
			RET

KEYDELAY:
			MOV		R0, #020H
REPEAT:
			MOV		R1, #0FFH
			DJNZ	R1, $
			DJNZ	R0, REPEAT
			RET

KEYINITIAL:
			MOV	    R1, #00H
			MOV	    A, #11101111B
			SETB	C

COLSCAN:
			MOV	    R0, A
			INC	    R1
			CALL	SUBKEY
	
			CJNE	A, #0FFH, RSCAN
			MOV	    A, R0
			SETB	C
			RRC	    A
			JNC	    NO_INPUT
			JMP	    COLSCAN

NO_INPUT:
			MOV		A, #4
			RET

RSCAN:	
    		MOV	R2, #00H
ROWSCAN:
			RRC	A
			JNC	MATRIX
			INC	R2
			JMP	ROWSCAN

MATRIX:
    		MOV	    A, R2
			MOV	    B, #05H
			MUL	    AB
			ADD	    A, R1
UP:			CJNE	A, #10H, LEFT
			MOV		A, #00H
			JMP		KEYEND
LEFT:		CJNE	A, #15H, DOWN
			MOV		A, #03H
			JMP		KEYEND
DOWN:		CJNE	A, #16H, RIGHT
			MOV		A, #02H
			JMP		KEYEND
RIGHT:		CJNE	A, #17H
			MOV		A, #01H
			JMP		KEYEND
WRONG:		MOV		A, #04H
KEYEND:		RET


SUBKEY:
    		MOV	    DPTR, #DATAOUT
			MOVX	@DPTR, A
			MOV	    DPTR, #DATAIN
			MOVX	A, @DPTR
			RET