SNAKE_LEN	EQU	30H
SNAKE_DIR	EQU	31H	;0 1 2 3 / UP R DOWN L
SNAKE_TAIL	EQU	32H

COLGREEN	EQU	0FFC5H	;DISPLAY INIT
COLRED		EQU	0FFC6H
ROW		EQU	0FFC7H

	ORG	8000H

INIT:	MOV	R2, #00H	;GREEN DOT OFF
	MOV	R0, #00H
	CALL	DOTCOLG

	MOV	R0, #SNAKE_LEN	;INIT LENGTH -> 3
	MOV	@R0, #3
	MOV	SNAKE_DIR, #1	;INIT DIRECTION -> 2

	MOV	32H, #00H	;0000/0000B, TAIL
	MOV	33H, #01H	;0000/0001B
	MOV	34H, #02H	;0000/0010B, HEAD

LOOP:

--------------------------------------
DISPLAY:
	MOV A, #SNAKE_TAIL
	MOV R2, SNAKE_LEN
	MOV R1, #00000001B
	
	

	ADD A, #1

	MOV A, R0
	CALL DOTCOLR
	RET
	
	
DOTCOLG:			;GREEN, EGG
	MOV	DPTR, #COLGREEN
	MOV	A, R2
	MOVX	@DPTR, A
	
	MOV	DPTR, #ROW
	MOV	A, R0
	MOVX	@DPTR, A
	RET

DOTCOLR:			;RED, SNAKE
	MOV	DPTR, #COLRED
	MOV	A, R1
	MOVX	@DPTR, A
	
	MOV	DPTR, #ROW
	MOV	A, R0
	MOVX	@DPTR, A
	RET